# Generated by Django 2.2 on 2019-05-16 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 14, 5, 45, 780213), verbose_name='date published'),
        ),
    ]
