# Generated by Django 2.2 on 2019-05-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0003_auto_20190520_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 12, 19, 20, 928855), verbose_name='date published'),
        ),
    ]
