# Generated by Django 2.2 on 2019-05-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0004_auto_20190521_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 12, 19, 35, 272283), verbose_name='date published'),
        ),
    ]
