# Generated by Django 2.2 on 2019-05-21 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0008_auto_20190521_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 12, 28, 2, 649390), verbose_name='date published'),
        ),
    ]
