# Generated by Django 2.2 on 2019-05-22 16:02

from django.db import migrations, models
import micro.models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0010_auto_20190521_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=micro.models.get_image_path),
        ),
    ]
